SOURCES_TOOLS = random.cc \
                hash.cc \
                etc.cc \
                convert.cc \
                genhash.cc

SOURCES =   random.cc \
            hash.cc \
            permutation.cc \
            crypt.cc \
            ecc.cc \
            signature.cc \
            filters.cc \
            rc32.cc \
            nvoc.cc \
            lzss.cc \
            etc.cc \
            convert.cc \
            fnode.cc \
            bnode.cc \
            ftree.cc \
            canonicalize.cc \
            mdirs.cc \
            timebits.cc \
            archive.cc \
            getpasswd.cc \
            globfunction.cc \
            axisum.cc \
            vars.cc \
            axismain.cc
